contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #buildrnaseqbundle channel"
    url: https://nfcore.slack.com/channels/buildrnaseqbundle
    about: Discussion about the nf-core/buildrnaseqbundle pipeline
